python convert_to_py.py console7
python convert_to_py.py dos16
python convert_to_py.py dos8
python convert_to_py.py galaxy16_digits
python convert_to_py.py galaxy24_digits
python convert_to_py.py micro8
python convert_to_py.py mini8
python convert_to_py.py sans16_unicode
python convert_to_py.py sans16B_unicode
python convert_to_py.py sans24
python convert_to_py.py sans24B
python convert_to_py.py squared16_unicode
python convert_to_py.py squared16B_unicode